Address issue #177 (untested)
In pygame.sysfont, this handles the OS X case where /usr/X11/bin/ft-list is
missing, leading to the unintended Python exception:

UnboundLocalError: local variable 'fonts' referenced before assignment